### PR TITLE
Write a function to the NEW GAME button in the game control panel #42

### PR DESCRIPTION
**Pull request by nazgul7d**
Hey guys,
I just finished working on the New Game button.

Users can see a button in the game control panel to start a new game, which:
 clears the grid - I reused the function for the ClearGrid feature
 starts a new game - it clears all the messages and rolls the dice again
 updates the Leaderboard - I wrote a function to reset Leaderboard values to 0

Please let me know if you have any comments

### CODE REVIEW

**Review by goodman2814 — COMMENTED** [review]
Great work! 

Should there be an onclick function added to the HTML for the New Game and Submit buttons?

And this isn't a big issue but we will have to rectify some of the id names as I had to add a few to make the enable buttons function.

**Review by goodman2814 — APPROVED** [review]
I am silly. I forgot all about best practices! I'll have to fix my code to match. Great work!

**Comment by nazgul7d** [comment]
> Great work!
> 
> Should there be an onclick function added to the HTML for the New Game and Submit buttons?
> 
> And this isn't a big issue but we will have to rectify some of the id names as I had to add a few to make the enable buttons function.

Hey Alex,
We don't need onclick for buttons as they are managed dynamically by JavaScript.

**Review by PaulaR-05 — APPROVED** [review]
Hey Naz! Great job, thank you so much!
@goodman2814 and @nazgul7d have great attention to detail, I loved the dynamic of the comments here. haha

**Pull request merged**
