### PR TITLE
When the timer ends a loss is tallied

### PR DESCRIPTION
**Pull request by goodman2814**
OK, so I went a little beyond the scope  (sorry) and shifted a few things around to make what I am trying to do work. This task is not fully completed. I'm making this PR so you can see where I am and make any suggestions. This is not finished, please do not merge. 

Here is what I did: 

- I made it so that when the timer runs out, a loss point is tallied in the Time is Up collum.
- created an endGame() function that will: 
-        clear ALL of the squares, both "occupied" and "blocked", 
-        stops the timer (buggy, doesn't work yet but the idea is there), 
-        clear any messages or text
-        adds a "press play to start a new game" message under the play button. 

- I added this function to the "New Game" button. 
- Shifted the code around to be more organized (but if you don't like where I put things, please feel free to move them where they make sense for you)
- There are bugs that need fixing but I know how to add points to the leaderboard. Just need to write the end-game conditions for the other win/loss columns.

### CODE REVIEW

**Comment by goodman2814** [comment]
I will be working on this all day tomorrow so let me know if you see something very wrong or have an idea on how something can be improved.

**Comment by goodman2814** [comment]
OK! I believe I have the score counter set up and the win/loss conditions in place. Once we add a second player to the mix, we can add more code to determine winners. Here is what I did:

- The stop timer function now works
- a point is tallied on the leaderboard for time running out, and skipping a turn twice. 
- filling the grid seems to be a bit buggy. still trying to solve how to check if the grid is filled. 
- created some global variables to make these functions work. 
- organized code to read easier. (please feel free to change if needed)
- I had to tweak a lot of code to implement the win/loss conditions. Everything should still work as it did. 

Please let me know if you have questions or see something that needs fixing. 
Thanks!

**Comment by PaulaR-05** [comment]
Alex, thanks a lot for putting it together!

**Comment by PaulaR-05** [comment]
Naz and Alex, I commit one change to fix the bug on the FULL GRID Function.
I found another bug in the TOTAL of wins/losses but did not find what was causing it. 
As soon as I fix the second bug, i will let you know :)

**Comment by PaulaR-05** [comment]
Hey team! Bug fixed :)

**Review by PaulaR-05 — APPROVED** [review]
Hey team, bug fixed. But I believe we should change our leaderboard, we talk more later :)

**Pull request merged**
